#  Aplicación Entrenamientos Gimnasio
services:
  python-21-gym:
    container_name: python-21-gym
    image: 'python:3.14-slim'
    volumes:
      - .:/usr/python:ro                                      # código en el contenedor (solo lectura)
      # - /volume1/informatica/Python/config:/usr/config:ro    # variables de entorno (solo lectura)
      - /volume1/informatica/Python/bd/sqlite:/usr/bd:rw     # BD globales (lectura/escritura)
    working_dir: /usr/python
    restart: unless-stopped
    env_file:
      - /volume1/informatica/Python/config/app.env            # variables locales del proyecto .env
      # - /volume1/informatica/Python/$config/config.env       # variables globales desde volumen
    # environment:
      # - ENTORNO_JAVIER=produccion                 # también puedes definir variables extra aquí
    network_mode: host
    # ports:
      #- "${APP_PORT_CONTACTOS}:5010"               # usa variable del .env en el puerto
      #- 5011:5011                                  # puerto fijo (sin variable)
    command: "./ejecutar.sh"
